source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem "sinatra"
gem "sinatra-contrib", require: false
gem 'puma'
gem 'sinatra-websocket'

group :development, :test do
  gem "rerun"
end
